name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build & Release Executable
    runs-on: windows-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Build Standalone EXE
        shell: pwsh
        run: |
          .\tclkitsh.exe sdx.kit wrap ratioghost.exe -runtime .\tclkit.exe -vfs rghost.vfs

      - name: Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ratioghost.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
